[package]
name = "factorio-mods-fixer"
version = "0.1.0"
edition = "2021"

[dependencies]
full_moon = { version = "1.1.0", features = ["lua52"] }
owo-colors = "4.1.0"
stylua = { version = "0.20.0", features = ["lua52"] }
